name: WalkersMedal
version: 1.0
main: walkersmedal.walkersmedal.WalkersMedal
api-version: 1.18

permissions:
  WalkCountCommandAllowUse:
    default: OP
  WalkersMedalTraderCommandAllowUse:
    default: OP

commands:
  filePreview:

  WalkCount:
    Permission: WalkCountCommandAllowUse
    usage: 'not player name'
  WalkersMedalTrader:
    Permission: WalkersMedalTraderCommandAllowUse
  WalkersMedalPermission:
    Permission: OP
  Given:
    Default: OP
  test:
    Default: OP